<a href="https://colab.research.google.com/github/cpython-projects/python_da_06_11_25/blob/main/lesson_14_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Розвідка та діагностика якості даних

**Датасет:** [House Sales in King County, USA (Kaggle)](https://www.kaggle.com/datasets/harlfoxem/housesalesprediction)
Файл: `kc_house_data.csv`

---

### 🎯 Мета завдання

Провести **первинний аналіз і діагностику даних**, виявити **проблемні ознаки (стовпці)** та описати типові **помилки і можливі способи їх виправлення**.

### 🔹 Частина 1. Первинне знайомство

1. Завантажте датасет `kc_house_data.csv`.
2. Виведіть загальну інформацію про дані (`.info()`).
3. Подивіться перші 5 рядків (`.head()`).
4. Дізнайтеся кількість рядків та стовпців.

**Питання:**

* Скільки всього ознак і спостережень?
* Чи є ознаки, які виглядають як числові, але насправді є рядковими (або навпаки)?

In [1]:
from google.colab import files
uploaded = files.upload()

Saving kc_house_data.csv to kc_house_data.csv


In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('kc_house_data.csv')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [6]:
df.shape

(21613, 21)

### 🔹 Частина 2. Перевірка на дублікати

1. Знайдіть кількість повних дублікатів рядків.
2. Якщо дублікати є — покажіть приклади.
3. Вирішіть, чи варто їх видаляти і чому.

In [7]:
df.duplicated().sum()

np.int64(0)

### 🔹 Частина 3. Аналіз пропусків

1. Порахуйте кількість пропусків по кожному стовпцю.
2. Побудуйте рейтинг стовпців за кількістю пропусків (від більшого до меншого).
3. Знайдіть ознаки, де пропусків **більше 20%**.
4. Прокоментуйте: які з цих ознак можна видалити, а які варто спробувати відновити?

In [12]:
df.isna().sum()


id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [9]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

### 🔹 Частина 4. Типи даних

1. Перевірте, чи відповідають типи даних вмісту.
2. Знайдіть ознаки, у яких:

   * числовий тип, але категоріальний сенс;
   * рядковий тип, але можливо містять числа.
3. Запропонуйте, де потрібно змінити тип (`astype`, `pd.to_numeric`, `category` тощо).

In [13]:
df.date.unique()

array(['20141013T000000', '20141209T000000', '20150225T000000',
       '20150218T000000', '20140512T000000', '20140627T000000',
       '20150115T000000', '20150415T000000', '20150312T000000',
       '20150403T000000', '20140527T000000', '20140528T000000',
       '20141007T000000', '20150124T000000', '20140731T000000',
       '20140529T000000', '20141205T000000', '20150424T000000',
       '20140514T000000', '20140826T000000', '20140703T000000',
       '20140516T000000', '20141120T000000', '20141103T000000',
       '20140626T000000', '20141201T000000', '20140624T000000',
       '20150302T000000', '20141110T000000', '20141203T000000',
       '20140613T000000', '20141230T000000', '20150213T000000',
       '20140620T000000', '20140715T000000', '20140811T000000',
       '20140707T000000', '20141028T000000', '20140729T000000',
       '20140718T000000', '20150325T000000', '20140716T000000',
       '20150428T000000', '20150311T000000', '20140916T000000',
       '20150217T000000', '20141231T0000

In [16]:
df['date'] = pd.to_datetime(df['date'])

In [17]:
df['waterfront'].unique()

array([0, 1])

In [18]:
df['waterfront'] = df['waterfront'].astype('bool')

In [19]:
df['view'].unique()

array([0, 3, 4, 2, 1])

In [20]:
df['view'] = pd.Categorical(df['view'], ordered=True, categories=[0, 1, 2, 3, 4])

In [21]:
df['grade'].unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13,  1])

In [22]:
grades = list(range(1, 14))
df['grade'] = pd.Categorical(df['grade'], ordered=True, categories=grades)

In [23]:
grades

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [24]:
df['condition'].unique()

array([3, 5, 4, 1, 2])

In [27]:
df['condition'] = pd.Categorical(df['condition'], ordered=True, categories=[1, 2, 3, 4, 5])

### 🔹 Частина 5. Базова статистика

1. Для числових стовпців обчисліть:

   * середнє (`mean`),
   * медіану (`median`),
   * мінімум і максимум.
2. Знайдіть аномальні значення (наприклад, нулі там, де їх бути не повинно: площа, кількість кімнат тощо; середнє і медіана значно відрізняються).
3. Наведіть **2–3 приклади підозрілих ознак**.

In [28]:
df.describe()

id                           date         price  \
count  2.161300e+04                          21613  2.161300e+04   
mean   4.580302e+09  2014-10-29 04:38:01.959931648  5.400881e+05   
min    1.000102e+06            2014-05-02 00:00:00  7.500000e+04   
25%    2.123049e+09            2014-07-22 00:00:00  3.219500e+05   
50%    3.904930e+09            2014-10-16 00:00:00  4.500000e+05   
75%    7.308900e+09            2015-02-17 00:00:00  6.450000e+05   
max    9.900000e+09            2015-05-27 00:00:00  7.700000e+06   
std    2.876566e+09                            NaN  3.671272e+05   

           bedrooms     bathrooms   sqft_living      sqft_lot        floors  \
count  21613.000000  21613.000000  21613.000000  2.161300e+04  21613.000000   
mean       3.370842      2.114757   2079.899736  1.510697e+04      1.494309   
min        0.000000      0.000000    290.000000  5.200000e+02      1.000000   
25%        3.000000      1.750000   1427.000000  5.040000e+03      1.000000   
50%        3.000000      2.250000   1910.000000  7.618000e+03      1.500000   
75%        4.000000      2.500000   2550.000000  1.068800e+04      2.000000   
max       33.000000      8.000000  13540.000000  1.651359e+06      3.500000   
std        0.930062      0.770163    918.440897  4.142051e+04      0.539989   

         sqft_above  sqft_basement      yr_built  yr_renovated       zipcode  \
count  21613.000000   21613.000000  21613.000000  21613.000000  21613.000000   
mean    1788.390691     291.509045   1971.005136     84.402258  98077.939805   
min      290.000000       0.000000   1900.000000      0.000000  98001.000000   
25%     1190.000000       0.000000   1951.000000      0.000000  98033.000000   
50%     1560.000000       0.000000   1975.000000      0.000000  98065.000000   
75%     2210.000000     560.000000   1997.000000      0.000000  98118.000000   
max     9410.000000    4820.000000   2015.000000   2015.000000  98199.000000   
std      828.090978     442.575043     29.373411    401.679240     53.505026   

                lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000   21613.000000   21613.000000  
mean      47.560053   -122.213896    1986.552492   12768.455652  
min       47.155900   -122.519000     399.000000     651.000000  
25%       47.471000   -122.328000    1490.000000    5100.000000  
50%       47.571800   -122.230000    1840.000000    7620.000000  
75%       47.678000   -122.125000    2360.000000   10083.000000  
max       47.777600   -121.315000    6210.000000  871200.000000  
std        0.138564      0.140828     685.391304   27304.179631

In [29]:
df['price'].skew()

np.float64(4.024069144684712)

### 🔹 Частина 6. Інтерпретація результатів

Складіть короткий **звіт (5–7 речень)**:

* Які типи проблем ви виявили?
* Скільки ознак потенційно потребують перетворення або очистки?
* Які три ознаки ви б точно **видалили або виправили в першу чергу**, і чому?